# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
   
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      
      
    - name: GitHub Action for Yarn
#       uses: Borales/actions-yarn@v2.3.0
      uses: actions/setup-node@v1
      with:
    # Yarn command
       cmd: install
    - name: build production
      run : npm run build
      working-directory: my-app
        
    - name: intalling surge
      working-directory: my-app

      run : npm install -g surge
      
    - name: deploying on surge
      working-directory: my-app
      run : surge http://bootcamp20221.surge.sh/ --token ${{secrets.REACT_SURGE_TOKEN}}
